<?php

/**
 * @file
 * Contains multistep_form_showcase.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function multistep_form_showcase_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the multistep_form_showcase module.
    case 'help.page.multistep_form_showcase':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a module to showcase how to code a Drupal multistep form.') . '</p>';
      return $output;

    default:
  }
}
